version: "2"

services:
  nginx-videos:
    image: nginx:1.25-alpine
    container_name: nginx-videos
    volumes:
      - videos-up1:/usr/share/nginx/html/videos:ro

volumes:
  videos-up1:
    driver: rclone # mkdir /var/lib/docker-plugins/rclone/{config,cache} && ln -s /root/.config/rclone/rclone.conf /var/lib/docker-plugins/rclone/config && docker plugin install rclone/docker-volume-rclone:arm64 args="-v" --alias rclone --grant-all-permissions
    driver_opts:
      remote: storagebox:videos
      gid: 101
      uid: 101
      # allow_other: 'true'
      # vfs_cache_mode: full
      # poll_interval: 0
