services:
  mailserver:
    container_name: mailserver
    image: mailserver/docker-mailserver:14.0.0
    hostname: mail.bojidar-bg.com ## <- MX
    env_file: docker-mailserver/mailserver.env
    environment:
      #OVERRIDE_HOSTNAME:
      LOG_LEVEL: info
      #SUPERVISOR_LOGLEVEL:
      #DMS_VMAIL_UID:
      #DMS_VMAIL_GID:
      #ACCOUNT_PROVISIONER:
      #POSTMASTER_ADDRESS:
      ENABLE_UPDATE_CHECK: 0
      #UPDATE_CHECK_INTERVAL:
      PERMIT_DOCKER: none
      #TZ:
      #NETWORK_INTERFACE:
      #TLS_LEVEL:
      #SPOOF_PROTECTION:
      ENABLE_SRS: 0
      ENABLE_OPENDKIM: 0
      ENABLE_OPENDMARC: 0
      ENABLE_POLICYD_SPF: 0
      #ENABLE_POP3:
      ENABLE_IMAP: 1
      ENABLE_CLAMAV: 0
      #SPAM_SUBJECT:
      ENABLE_RSPAMD: 1
      #ENABLE_RSPAMD_REDIS:
      RSPAMD_LEARN: 1
      RSPAMD_CHECK_AUTHENTICATED: 0
      RSPAMD_GREYLISTING: 0
      RSPAMD_HFILTER: 1
      RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE: 6
      RSPAMD_NEURAL: 0
      MOVE_SPAM_TO_JUNK: 1
      MARK_SPAM_AS_READ: 0
      ENABLE_AMAVIS: 0
      AMAVIS_LOGLEVEL: 0
      ENABLE_DNSBL: 0
      ENABLE_FAIL2BAN: 0
      FAIL2BAN_BLOCKTYPE: drop
      #ENABLE_MANAGESIEVE:
      POSTSCREEN_ACTION: enforce
      #SMTP_ONLY:
      #VIRUSMAILS_DELETE_DELAY:
      #POSTFIX_DAGENT:
      #POSTFIX_MAILBOX_SIZE_LIMIT:
      ENABLE_QUOTAS: 1
      #POSTFIX_MESSAGE_SIZE_LIMIT:
      #CLAMAV_MESSAGE_SIZE_LIMIT:
      #PFLOGSUMM_TRIGGER:
      #PFLOGSUMM_RECIPIENT:
      #PFLOGSUMM_SENDER:
      #LOGWATCH_INTERVAL:
      #LOGWATCH_RECIPIENT:
      #LOGWATCH_SENDER:
      #REPORT_RECIPIENT:
      #REPORT_SENDER:
      LOGROTATE_INTERVAL: weekly
      LOGROTATE_COUNT: 4
      POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME: 0
      POSTFIX_INET_PROTOCOLS: all
      ENABLE_MTA_STS: 0
      DOVECOT_INET_PROTOCOLS: all
      ENABLE_SPAMASSASSIN: 0
      ENABLE_SPAMASSASSIN_KAM: 0
      #SPAMASSASSIN_SPAM_TO_INBOX: 1
      #SA_TAG: 2.0
      #SA_TAG2: 6.31
      #SA_KILL: 10.0
      ENABLE_FETCHMAIL: 0
      #FETCHMAIL_POLL: 300
      #FETCHMAIL_PARALLEL: 0
      ENABLE_GETMAIL: 0
      #GETMAIL_POLL: 5
      #ENABLE_OAUTH2:
      #OAUTH2_INTROSPECTION_URL:
      #LDAP_START_TLS:
      #LDAP_SERVER_HOST:
      #LDAP_SEARCH_BASE:
      #LDAP_BIND_DN:
      #LDAP_BIND_PW:
      #LDAP_QUERY_FILTER_USER:
      #LDAP_QUERY_FILTER_GROUP:
      #LDAP_QUERY_FILTER_ALIAS:
      #LDAP_QUERY_FILTER_DOMAIN:
      #DOVECOT_TLS:
      #DOVECOT_USER_FILTER:
      #DOVECOT_PASS_FILTER:
      DOVECOT_MAILBOX_FORMAT: maildir
      #DOVECOT_AUTH_BIND:
      ENABLE_POSTGREY: 0
      POSTGREY_DELAY: 300
      POSTGREY_MAX_AGE: 35
      POSTGREY_TEXT: "Delayed by Postgrey"
      POSTGREY_AUTO_WHITELIST_CLIENTS: 5
      ENABLE_SASLAUTHD: 0
      #SASLAUTHD_MECHANISMS:
      #SASLAUTHD_MECH_OPTIONS:
      #SASLAUTHD_LDAP_SERVER:
      #SASLAUTHD_LDAP_BIND_DN:
      #SASLAUTHD_LDAP_PASSWORD:
      #SASLAUTHD_LDAP_SEARCH_BASE:
      #SASLAUTHD_LDAP_FILTER:
      #SASLAUTHD_LDAP_START_TLS:
      #SASLAUTHD_LDAP_TLS_CHECK_PEER:
      #SASLAUTHD_LDAP_TLS_CACERT_FILE:
      #SASLAUTHD_LDAP_TLS_CACERT_DIR:
      #SASLAUTHD_LDAP_PASSWORD_ATTR:
      #SASLAUTHD_LDAP_AUTH_METHOD:
      #SASLAUTHD_LDAP_MECH:
      #SRS_SENDER_CLASSES: envelope_sender
      #SRS_EXCLUDE_DOMAINS:
      #SRS_SECRET:
      #DEFAULT_RELAY_HOST:
      #RELAY_HOST:
      #RELAY_PORT: 25
      #RELAY_USER:
      #RELAY_PASSWORD:
      SSL_TYPE: letsencrypt
      #SSL_CERT_PATH:
      #SSL_KEY_PATH:
      #SSL_ALT_CERT_PATH:
      #SSL_ALT_KEY_PATH:
      VIRTUAL_HOST: mail.bojidar-bg.dev
      LETSENCRYPT_HOST: mail.bojidar-bg.dev
    ports: # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
      #- "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: certs
        target: /etc/letsencrypt/live/mail.bojidar-bg.dev
        read_only: true
        volume:
          subpath: mail.bojidar-bg.dev
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
volumes:
  mail_data:
  mail_state:
  mail_logs:
  mail_config:
  # certs: -- import from docker-compose-nginx.yml!!!
