services:
  # Frontend
  jitsi-web:
    image: jitsi/web:stable-9584-1
    restart: unless-stopped
    volumes:
    - target: /config
      source: jitsi-config
      volume:
        subpath: web
      type: volume
    - target: /var/spool/cron/crontabs
      source: jitsi-config
      volume:
        subpath: web/crontabs
      type: volume
    - target: /usr/share/jitsi-meet/transcripts
      source: jitsi-config
      volume:
        subpath: transcripts
      type: volume
    - ./jitsi-hack-svc1:/etc/cont-init.d/50-jitsi-hack-svc:ro
    environment:
      # AMPLITUDE_ID:
      # ANALYTICS_SCRIPT_URLS:
      # ANALYTICS_WHITELISTED_EVENTS:
      # AUDIO_QUALITY_OPUS_BITRATE:
      # AUTO_CAPTION_ON_RECORD:
      # BRANDING_DATA_URL:
      # BOSH_RELATIVE:
      # CHROME_EXTENSION_BANNER_JSON:
      # COLIBRI_WEBSOCKET_PORT:
      COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME: jitsi-jvb
      # COLIBRI_WEBSOCKET_REGEX:
      # CONFCODE_URL:
      # CORS_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN:
      DEFAULT_LANGUAGE: bg
      # DEPLOYMENTINFO_ENVIRONMENT:
      # DEPLOYMENTINFO_ENVIRONMENT_TYPE:
      # DEPLOYMENTINFO_REGION:
      # DEPLOYMENTINFO_SHARD:
      # DEPLOYMENTINFO_USERREGION:
      # DESKTOP_SHARING_FRAMERATE_AUTO:
      # DESKTOP_SHARING_FRAMERATE_MIN:
      # DESKTOP_SHARING_FRAMERATE_MAX:
      # DIALIN_NUMBERS_URL:
      # DIALOUT_AUTH_URL:
      # DIALOUT_CODES_URL:
      # DISABLE_AUDIO_LEVELS:
      # DISABLE_COLIBRI_WEBSOCKET_JVB_LOOKUP:
      # DISABLE_DEEP_LINKING:
      # DISABLE_GRANT_MODERATOR:
      DISABLE_HTTPS: 1
      # DISABLE_KICKOUT:
      DISABLE_LOCAL_RECORDING: 0
      # DISABLE_POLLS:
      # DISABLE_PRIVATE_CHAT:
      # DISABLE_PROFILE:
      # DISABLE_REACTIONS:
      # DISABLE_REMOTE_VIDEO_MENU:
      # DISABLE_START_FOR_ALL:
      # DROPBOX_APPKEY:
      # DROPBOX_REDIRECT_URI:
      # DYNAMIC_BRANDING_URL:
      # ENABLE_AUDIO_PROCESSING:
      ENABLE_AUTH: 1
      ENABLE_GUESTS: 1
      # ENABLE_AUTH_DOMAIN:
      ENABLE_BREAKOUT_ROOMS: 1
      # ENABLE_CALENDAR:
      ENABLE_COLIBRI_WEBSOCKET: 1
      # ENABLE_COLIBRI_WEBSOCKET_UNSAFE_REGEX:
      # ENABLE_E2EPING:
      # ENABLE_FILE_RECORDING_SHARING:
      # ENABLE_HSTS:
      # ENABLE_HTTP_REDIRECT:
      # ENABLE_IPV6:
      ENABLE_LETSENCRYPT: 0
      # ENABLE_NO_AUDIO_DETECTION:
      # ENABLE_NOISY_MIC_DETECTION:
      # ENABLE_OCTO:
      # ENABLE_OPUS_RED:
      ENABLE_PREJOIN_PAGE: 1
      ENABLE_P2P: 1
      ENABLE_WELCOME_PAGE: 0
      ENABLE_CLOSE_PAGE: 0
      ENABLE_LIVESTREAMING: 0
      # ENABLE_LIVESTREAMING_DATA_PRIVACY_LINK:
      # ENABLE_LIVESTREAMING_HELP_LINK:
      # ENABLE_LIVESTREAMING_TERMS_LINK:
      # ENABLE_LIVESTREAMING_VALIDATOR_REGEXP_STRING:
      # ENABLE_LOAD_TEST_CLIENT:
      ENABLE_LOCAL_RECORDING_NOTIFY_ALL_PARTICIPANT: 1
      # ENABLE_LOCAL_RECORDING_SELF_START:
      ENABLE_RECORDING: 1
      # ENABLE_REMB:
      # ENABLE_REQUIRE_DISPLAY_NAME:
      # ENABLE_SERVICE_RECORDING:
      # ENABLE_SIMULCAST:
      # ENABLE_STATS_ID:
      # ENABLE_STEREO:
      # ENABLE_SUBDOMAINS:
      # ENABLE_TALK_WHILE_MUTED:
      # ENABLE_TCC:
      ENABLE_TRANSCRIPTIONS: 0
      # TRANSLATION_LANGUAGES:
      # TRANSLATION_LANGUAGES_HEAD:
      # USE_APP_LANGUAGE:
      # PREFERRED_LANGUAGE:
      # ENABLE_XMPP_WEBSOCKET:
      ENABLE_JAAS_COMPONENTS: 0
      # ETHERPAD_PUBLIC_URL:
      # ETHERPAD_URL_BASE:
      # E2EPING_NUM_REQUESTS:
      # E2EPING_MAX_CONFERENCE_SIZE:
      # E2EPING_MAX_MESSAGE_PER_SECOND:
      # GOOGLE_ANALYTICS_ID:
      # GOOGLE_API_APP_CLIENT_ID:
      HIDE_PREMEETING_BUTTONS: 0
      HIDE_PREJOIN_DISPLAY_NAME: 0
      HIDE_PREJOIN_EXTRA_BUTTONS: 0
      # INVITE_SERVICE_URL:
      # JVB_PREFER_SCTP:
      # LETSENCRYPT_USE_STAGING:
      # MATOMO_ENDPOINT:
      # MATOMO_SITE_ID:
      # MICROSOFT_API_APP_CLIENT_ID:
      # NGINX_RESOLVER:
      # NGINX_WORKER_PROCESSES:
      # NGINX_WORKER_CONNECTIONS:
      # PEOPLE_SEARCH_URL:
      # P2P_PREFERRED_CODEC:
      # RESOLUTION:
      # RESOLUTION_MIN:
      # RESOLUTION_WIDTH:
      # RESOLUTION_WIDTH_MIN:
      # START_AUDIO_MUTED:
      # START_AUDIO_ONLY:
      # START_SILENT:
      # START_WITH_AUDIO_MUTED:
      # START_VIDEO_MUTED:
      # START_WITH_VIDEO_MUTED:
      # TESTING_AV1_SUPPORT:
      # TOKEN_AUTH_URL:
      # TOOLBAR_BUTTONS:
      TZ:
      # VIDEOQUALITY_BITRATE_H264_LOW:
      # VIDEOQUALITY_BITRATE_H264_STANDARD:
      # VIDEOQUALITY_BITRATE_H264_HIGH:
      # VIDEOQUALITY_BITRATE_H264_FULL:
      # VIDEOQUALITY_BITRATE_H264_ULTRA:
      # VIDEOQUALITY_BITRATE_H264_SS_HIGH:
      # VIDEOQUALITY_BITRATE_VP8_LOW:
      # VIDEOQUALITY_BITRATE_VP8_STANDARD:
      # VIDEOQUALITY_BITRATE_VP8_HIGH:
      # VIDEOQUALITY_BITRATE_VP8_FULL:
      # VIDEOQUALITY_BITRATE_VP8_ULTRA:
      # VIDEOQUALITY_BITRATE_VP8_SS_HIGH:
      # VIDEOQUALITY_BITRATE_VP9_LOW:
      # VIDEOQUALITY_BITRATE_VP9_STANDARD:
      # VIDEOQUALITY_BITRATE_VP9_HIGH:
      # VIDEOQUALITY_BITRATE_VP9_FULL:
      # VIDEOQUALITY_BITRATE_VP9_ULTRA:
      # VIDEOQUALITY_BITRATE_VP9_SS_HIGH:
      # VIDEOQUALITY_BITRATE_AV1_LOW:
      # VIDEOQUALITY_BITRATE_AV1_STANDARD:
      # VIDEOQUALITY_BITRATE_AV1_HIGH:
      # VIDEOQUALITY_BITRATE_AV1_FULL:
      # VIDEOQUALITY_BITRATE_AV1_ULTRA:
      # VIDEOQUALITY_BITRATE_AV1_SS_HIGH:
      # VIDEOQUALITY_PREFERRED_CODEC:
      # XMPP_AUTH_DOMAIN:
      XMPP_BOSH_URL_BASE: "http://jitsi-xmpp:5280"
      # XMPP_DOMAIN:
      # XMPP_GUEST_DOMAIN:
      # XMPP_MUC_DOMAIN:
      # XMPP_RECORDER_DOMAIN:
      # XMPP_PORT:
      WHITEBOARD_COLLAB_SERVER_PUBLIC_URL: "https://jitsi-wb.bojidar-bg.dev"
      WHITEBOARD_COLLAB_SERVER_URL_BASE: "http://jitsi-whiteboard"
      PUBLIC_URL: "https://jitsi.bojidar-bg.dev"
      VIRTUAL_HOST: "jitsi.bojidar-bg.dev"
      LETSENCRYPT_HOST: "jitsi.bojidar-bg.dev"
    depends_on:
      - jitsi-jvb

  # XMPP server
  jitsi-prosody:
    container_name: jitsi-xmpp
    image: jitsi/prosody:stable-9584-1
    restart: unless-stopped
    volumes:
    - jitsi-prosody-config:/config
    - ./jitsi-hack-svc2:/etc/cont-init.d/50-jitsi-hack-svc:ro
    # - jitsi-prosody-custom-plugins:/prosody-plugins-custom:Z
    environment:
      AUTH_TYPE: ldap
      # DISABLE_POLLS:
      ENABLE_AUTH: 1
      # ENABLE_AV_MODERATION:
      ENABLE_BREAKOUT_ROOMS: 1
      # ENABLE_END_CONFERENCE:
      ENABLE_GUESTS: 1
      # ENABLE_IPV6:
      # ENABLE_LOBBY:
      ENABLE_RECORDING: 1
      # ENABLE_S2S:
      # ENABLE_VISITORS:
      # ENABLE_XMPP_WEBSOCKET:
      ENABLE_JAAS_COMPONENTS: 0
      # GC_TYPE:
      # GC_INC_TH:
      # GC_INC_SPEED:
      # GC_INC_STEP_SIZE:
      # GC_GEN_MIN_TH:
      # GC_GEN_MAX_TH:
      # GLOBAL_CONFIG:
      # GLOBAL_MODULES:
      # JIBRI_RECORDER_USER:
      JIBRI_RECORDER_PASSWORD: ${JITSI_RECORDER_PASS:?JITSI_RECORDER_PASS}
      # JIBRI_SIP_BREWERY_MUC:
      # JIBRI_XMPP_USER:
      JIBRI_XMPP_PASSWORD: ${JITSI_JIBRI_PASS:?JITSI_JIBRI_PASS}
      JICOFO_AUTH_PASSWORD: ${JITSI_JICOFO_PASS:?JITSI_JICOFO_PASS}
      # JICOFO_COMPONENT_SECRET:
      # JIGASI_XMPP_USER:
      JIGASI_XMPP_PASSWORD: ${JITSI_JIGASI_PASS:?JITSI_JIGASI_PASS}
      # JVB_AUTH_USER:
      JVB_AUTH_PASSWORD: ${JITSI_JVB_PASS:?JITSI_JVB_PASS}
      # JWT_APP_ID:
      # JWT_APP_SECRET:
      # JWT_ACCEPTED_ISSUERS:
      # JWT_ACCEPTED_AUDIENCES:
      # JWT_ASAP_KEYSERVER:
      # JWT_ALLOW_EMPTY:
      # JWT_AUTH_TYPE:
      # JWT_ENABLE_DOMAIN_VERIFICATION:
      # JWT_SIGN_TYPE:
      # JWT_TOKEN_AUTH_MODULE:
      # MATRIX_UVS_URL:
      # MATRIX_UVS_ISSUER:
      # MATRIX_UVS_AUTH_TOKEN:
      # MATRIX_UVS_SYNC_POWER_LEVELS:
      # MATRIX_LOBBY_BYPASS:
      # LOG_LEVEL:
      LDAP_URL: "ldap://lldap:3890"
      LDAP_AUTH_METHOD: bind
      # LDAP_VERSION: 3
      # LDAP_TLS_CIPHERS:
      LDAP_TLS_CHECK_PEER: 0
      # LDAP_TLS_CACERT_FILE:
      # LDAP_TLS_CACERT_DIR:
      LDAP_START_TLS: 0
      LDAP_USE_TLS: 0
      LDAP_BINDDN: "uid=jitsi,ou=people,dc=bojidar-bg,dc=dev"
      LDAP_BINDPW: "${JITSI_LDAP_PASSWORD:?JITSI_LDAP_PASSWORD}"
      LDAP_BASE: ou=people,dc=bojidar-bg,dc=dev
      LDAP_FILTER: (&(|(uid=%u)(uid=%u@%r))(objectClass=person))
      # MAX_PARTICIPANTS:
      # PROSODY_ADMINS:
      # PROSODY_AUTH_TYPE:
      # PROSODY_C2S_LIMIT:
      # PROSODY_C2S_REQUIRE_ENCRYPTION:
      # PROSODY_RESERVATION_ENABLED:
      # PROSODY_RESERVATION_REST_BASE_URL:
      # PROSODY_ENABLE_RATE_LIMITS:
      # PROSODY_ENABLE_S2S:
      # PROSODY_ENABLE_METRICS:
      # PROSODY_GUEST_AUTH_TYPE:
      # PROSODY_HTTP_PORT:
      # PROSODY_LOG_CONFIG:
      # PROSODY_METRICS_ALLOWED_CIDR:
      # PROSODY_MODE:
      # PROSODY_RATE_LIMIT_LOGIN_RATE:
      # PROSODY_RATE_LIMIT_SESSION_RATE:
      # PROSODY_RATE_LIMIT_TIMEOUT:
      # PROSODY_RATE_LIMIT_ALLOW_RANGES:
      # PROSODY_RATE_LIMIT_CACHE_SIZE:
      # PROSODY_S2S_LIMIT:
      # PROSODY_S2S_PORT:
      # PROSODY_TRUSTED_PROXIES:
      # PROSODY_VISITOR_INDEX:
      # PROSODY_VISITORS_MUC_PREFIX:
      # PUBLIC_URL: "https://jitsi.bojidar-bg.dev"
      # STUN_HOST:
      # STUN_PORT:
      # TURN_CREDENTIALS:
      # TURN_HOST:
      # TURNS_HOST:
      # TURN_PORT:
      # TURNS_PORT:
      # TURN_TRANSPORT:
      TZ:
      # VISITORS_MAX_VISITORS_PER_NODE:
      # VISITORS_XMPP_DOMAIN:
      # VISITORS_XMPP_SERVER:
      # VISITORS_XMPP_PORT:
      # XMPP_BREAKOUT_MUC_MODULES:
      # XMPP_CONFIGURATION:
      # XMPP_DOMAIN:
      # XMPP_AUTH_DOMAIN:
      # XMPP_GUEST_DOMAIN:
      # XMPP_MUC_DOMAIN:
      # XMPP_INTERNAL_MUC_DOMAIN:
      # XMPP_LOBBY_MUC_MODULES:
      # XMPP_MODULES:
      # XMPP_MUC_MODULES:
      # XMPP_MUC_CONFIGURATION:
      # XMPP_INTERNAL_MUC_MODULES:
      # XMPP_RECORDER_DOMAIN:
      # XMPP_PORT:
      # XMPP_SERVER_S2S_PORT:
      # XMPP_SPEAKERSTATS_MODULES:

  # Focus component
  jitsi-jicofo:
    image: jitsi/jicofo:stable-9584-1
    restart: unless-stopped
    ports:
    - '127.0.0.1:${JICOFO_REST_PORT:-8888}:8888'
    volumes:
    - jicofo-config:/config
    environment:
      AUTH_TYPE: ldap
      # BRIDGE_AVG_PARTICIPANT_STRESS:
      # BRIDGE_STRESS_THRESHOLD:
      ENABLE_AUTH: 1
      # ENABLE_AUTO_OWNER:
      # ENABLE_CODEC_VP8:
      # ENABLE_CODEC_VP9:
      # ENABLE_CODEC_AV1:
      # ENABLE_CODEC_H264:
      # ENABLE_CODEC_OPUS_RED:
      # ENABLE_JVB_XMPP_SERVER:
      # ENABLE_OCTO:
      # ENABLE_OCTO_SCTP:
      ENABLE_RECORDING: 1
      # ENABLE_SCTP:
      # ENABLE_VISITORS:
      # ENABLE_AUTO_LOGIN:
      # JICOFO_AUTH_LIFETIME:
      JICOFO_AUTH_PASSWORD: ${JITSI_JICOFO_PASS:?JITSI_JICOFO_PASS}
      # JICOFO_AUTH_TYPE:
      # JICOFO_BRIDGE_REGION_GROUPS:
      # JICOFO_ENABLE_AUTH:
      # JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS:
      # JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT:
      # JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT:
      # JICOFO_CONF_SOURCE_SIGNALING_DELAYS:
      # JICOFO_CONF_MAX_AUDIO_SENDERS:
      # JICOFO_CONF_MAX_VIDEO_SENDERS:
      # JICOFO_CONF_STRIP_SIMULCAST:
      # JICOFO_CONF_SSRC_REWRITING:
      # JICOFO_ENABLE_HEALTH_CHECKS:
      # JICOFO_ENABLE_REST:
      # JICOFO_HEALTH_CHECKS_USE_PRESENCE:
      # JICOFO_MAX_MEMORY:
      # JICOFO_MULTI_STREAM_BACKWARD_COMPAT:
      # JICOFO_OCTO_REGION:
      # JICOFO_TRUSTED_DOMAINS:
      # JIBRI_BREWERY_MUC:
      # JIBRI_REQUEST_RETRIES:
      # JIBRI_PENDING_TIMEOUT:
      # JIGASI_BREWERY_MUC:
      # JIGASI_SIP_URI:
      # JIGASI_TRUSTED_DOMAINS:
      # JVB_BREWERY_MUC:
      # JVB_XMPP_AUTH_DOMAIN:
      # JVB_XMPP_INTERNAL_MUC_DOMAIN:
      # JVB_XMPP_PORT:
      # JVB_XMPP_SERVER:
      # MAX_BRIDGE_PARTICIPANTS:
      # OCTO_BRIDGE_SELECTION_STRATEGY:
      # PROSODY_VISITORS_MUC_PREFIX:
      SENTRY_DSN: 0
      # SENTRY_ENVIRONMENT:
      # SENTRY_RELEASE:
      TZ:
      # VISITORS_MAX_PARTICIPANTS:
      # VISITORS_MAX_VISITORS_PER_NODE:
      # VISITORS_XMPP_AUTH_DOMAIN:
      # VISITORS_XMPP_SERVER:
      # VISITORS_XMPP_DOMAIN:
      # XMPP_DOMAIN:
      # XMPP_AUTH_DOMAIN:
      # XMPP_INTERNAL_MUC_DOMAIN:
      # XMPP_MUC_DOMAIN:
      # XMPP_RECORDER_DOMAIN:
      XMPP_SERVER: jitsi-xmpp
      # XMPP_PORT:
      # MAX_SSRCS_PER_USER:
      # MAX_SSRC_GROUPS_PER_USER:
    depends_on:
      - jitsi-prosody

  # Video bridge
  jitsi-jvb:
    image: jitsi/jvb:stable-9584-1
    restart: unless-stopped
    ports:
    - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
    - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
    volumes:
    - jitsi-jvb-config:/config
    environment:
      # AUTOSCALER_SIDECAR_KEY_FILE:
      # AUTOSCALER_SIDECAR_KEY_ID:
      # AUTOSCALER_SIDECAR_GROUP_NAME:
      # AUTOSCALER_SIDECAR_HOST_ID:
      # AUTOSCALER_SIDECAR_INSTANCE_ID:
      # AUTOSCALER_SIDECAR_PORT:
      # AUTOSCALER_SIDECAR_REGION:
      # AUTOSCALER_SIDECAR_SHUTDOWN_POLLING_INTERVAL:
      # AUTOSCALER_SIDECAR_STATS_POLLING_INTERVAL:
      ENABLE_COLIBRI_WEBSOCKET: 1
      # ENABLE_JVB_XMPP_SERVER:
      # ENABLE_OCTO:
      # ENABLE_SCTP:
      # JVB_ADVERTISE_IPS:
      # JVB_ADVERTISE_PRIVATE_CANDIDATES:
      # JVB_AUTH_USER:
      JVB_AUTH_PASSWORD: ${JITSI_JVB_PASS:?JITSI_JVB_PASS}
      # JVB_BREWERY_MUC:
      # JVB_DISABLE_STUN:
      # JVB_DISABLE_XMPP:
      # JVB_INSTANCE_ID:
      # JVB_PORT:
      # JVB_MUC_NICKNAME:
      # JVB_STUN_SERVERS:
      # JVB_LOG_FILE:
      # JVB_OCTO_BIND_ADDRESS:
      # JVB_OCTO_REGION:
      # JVB_OCTO_RELAY_ID:
      # JVB_REQUIRE_VALID_ADDRESS:
      # JVB_WS_DOMAIN:
      # JVB_WS_SERVER_ID:
      # JVB_WS_TLS:
      # JVB_XMPP_AUTH_DOMAIN:
      # JVB_XMPP_INTERNAL_MUC_DOMAIN:
      # JVB_XMPP_PORT:
      # JVB_XMPP_SERVER:
      PUBLIC_URL: "https://jitsi.bojidar-bg.dev"
      SENTRY_DSN: 0
      # SENTRY_ENVIRONMENT:
      # SENTRY_RELEASE:
      # COLIBRI_REST_ENABLED:
      # SHUTDOWN_REST_ENABLED:
      TZ:
      # VIDEOBRIDGE_MAX_MEMORY:
      # XMPP_AUTH_DOMAIN:
      # XMPP_INTERNAL_MUC_DOMAIN:
      XMPP_SERVER: jitsi-xmpp
      # XMPP_PORT:
    depends_on:
    - jitsi-prosody

  jitsi-jibri:
    image: jitsi/jibri:stable-9584-1
    restart: unless-stopped
    volumes:
    - jibri-config:/config:Z
    - jitsi-recordings:/recordings:rw
    shm_size: '2gb'
    cap_add:
    - SYS_ADMIN
    environment:
      # AUTOSCALER_SIDECAR_KEY_FILE:
      # AUTOSCALER_SIDECAR_KEY_ID:
      # AUTOSCALER_SIDECAR_GROUP_NAME:
      # AUTOSCALER_SIDECAR_HOST_ID:
      # AUTOSCALER_SIDECAR_INSTANCE_ID:
      # AUTOSCALER_SIDECAR_PORT:
      # AUTOSCALER_SIDECAR_REGION:
      # AUTOSCALER_SIDECAR_SHUTDOWN_POLLING_INTERVAL:
      # AUTOSCALER_SIDECAR_STATS_POLLING_INTERVAL:
      # AUTOSCALER_URL:
      CHROMIUM_FLAGS:
      DISPLAY: ":0"
      # ENABLE_STATS_D:
      # IGNORE_CERTIFICATE_ERRORS:
      # JIBRI_WEBHOOK_SUBSCRIBERS:
      # JIBRI_INSTANCE_ID:
      # JIBRI_ENABLE_PROMETHEUS:
      # JIBRI_HTTP_API_EXTERNAL_PORT:
      # JIBRI_HTTP_API_INTERNAL_PORT:
      # JIBRI_RECORDING_RESOLUTION:
      # JIBRI_RECORDING_VIDEO_ENCODE_PRESET:
      # JIBRI_RECORDING_CONSTANT_RATE_FACTOR:
      # JIBRI_RECORDING_FRAMERATE:
      # JIBRI_RECORDING_QUEUE_SIZE:
      # JIBRI_RECORDING_STREAMING_MAX_BITRATE:
      # JIBRI_USAGE_TIMEOUT:
      # JIBRI_XMPP_USER:
      JIBRI_XMPP_PASSWORD: ${JITSI_JIBRI_PASS:?JITSI_JIBRI_PASS}
      # JIBRI_XORG_HORIZ_SYNC:
      # JIBRI_XORG_VERT_REFRESH:
      # JIBRI_BREWERY_MUC:
      # JIBRI_RECORDER_USER:
      JIBRI_RECORDER_PASSWORD: ${JITSI_RECORDER_PASS:?JITSI_RECORDER_PASS}
      JIBRI_RECORDING_DIR: /recordings
      JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /usr/bin/true
      # JIBRI_STRIP_DOMAIN_JID:
      # JIBRI_STATSD_HOST:
      # JIBRI_STATSD_PORT:
      # LOCAL_ADDRESS:
      PUBLIC_URL: "https://jitsi.bojidar-bg.dev"
      TZ:
      # XMPP_AUTH_DOMAIN:
      # XMPP_DOMAIN:
      # XMPP_INTERNAL_MUC_DOMAIN:
      # XMPP_MUC_DOMAIN:
      # XMPP_RECORDER_DOMAIN:
      XMPP_SERVER: jitsi-xmpp
      # XMPP_PORT:
      # XMPP_TRUST_ALL_CERTS:
    depends_on:
    - jitsi-jicofo

  jitsi-whiteboard:
    container_name: jitsi-whiteboard
    image: jitsi/excalidraw-backend:21
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "jitsi-wb.bojidar-bg.dev"
      LETSENCRYPT_HOST: "jitsi-wb.bojidar-bg.dev"
    depends_on:
    - jitsi-web

volumes:
  jitsi-config:
  jitsi-prosody-config:
  jicofo-config:
  jibri-config:
  jitsi-jvb-config:
  jitsi-recordings:
    driver: rclone
    driver_opts:
      remote: 'storagebox:recordings'
      gid: 101
      uid: 101
      allow_other: 'true'
      vfs_cache_mode: writes
      # poll_interval: 0
