services:
  lldap:
    container_name: lldap
    image: lldap/lldap:2024-07-20-alpine
    volumes:
      - "lldap_data:/data"
    environment:
      #- UID=####
      #- GID=####
      #- TZ=####/####
      LLDAP_JWT_SECRET: "${LLDAP_JWT_SECRET:?LLDAP_JWT_SECRET}"
      LLDAP_KEY_SEED: "${LLDAP_KEY_SEED:?LLDAP_KEY_SEED}"
      LLDAP_LDAP_BASE_DN: "dc=bojidar-bg,dc=dev"

      LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
      LLDAP_SMTP_OPTIONS__SERVER: "mail.bojidar-bg.dev"
      LLDAP_SMTP_OPTIONS__PORT: "465"
      LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "TLS"
      LLDAP_SMTP_OPTIONS__USER: "lldap@bojidar-bg.dev"
      LLDAP_SMTP_OPTIONS__PASSWORD: "${LLDAP_SMTP_PASSWORD:?LLDAP_SMTP_PASSWORD}"
      LLDAP_SMTP_OPTIONS__FROM: "LLDAP - bojidar-bg.dev <lldap@bojidar-bg.dev>"
      LLDAP_SMTP_OPTIONS__REPLY_TO: "Do not reply <noreply@bojidar-bg.dev>"

      LLDAP_HTTP_URL: "http://auth.bojidar-bg.dev"
      VIRTUAL_HOST: "auth.bojidar-bg.dev"
      VIRTUAL_PORT: "17170"
      LETSENCRYPT_HOST: "auth.bojidar-bg.dev"

volumes:
  lldap_data:
