version: "2"
services:
  database:
    container_name: zulip-postgres
    image: "zulip/zulip-postgresql:14"
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_DB: "zulip"
      POSTGRES_USER: "zulip"
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: "${ZULIP_POSTGRESS_PASS:?ZULIP_POSTGRESS_PASS}"
    volumes:
      - "postgresql-14:/var/lib/postgresql/data:rw"
  memcached:
    container_name: zulip-memcached
    image: "memcached:1-alpine"
    pull_policy: always
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: "/home/memcache/memcached.conf"
      MEMCACHED_SASL_PWDB: "/home/memcache/memcached-sasl-db"
      MEMCACHED_PASSWORD: "${ZULIP_MEMCACHED_PASS:?ZULIP_MEMCACHED_PASS}"
  rabbitmq:
    container_name: zulip-rabbitmq
    image: "rabbitmq:3.7.7"
    pull_policy: always
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "${ZULIP_RABBITMQ_PASS:?ZULIP_RABBITMQ_PASS}"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq:rw"
  redis:
    container_name: zulip-redis
    image: "redis:7.2.4-alpine"
    pull_policy: always
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: "${ZULIP_REDIS_PASS:?ZULIP_REDIS_PASS}"
    volumes:
      - "redis:/data:rw"
  zulip:
    container_name: zulip-zulip
    image: "zulip/docker-zulip"
    build:
      context: docker-zulip
      dockerfile: Dockerfile
      args:
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: "8.3"

    pull_policy: build
    # command:
    #   - "sh"
    #   - "-euc"
    #   - |
    #     crudini --set /etc/zulip/zulip.conf application_server uwsgi_processes "3"
    #     exec /sbin/entrypoint.sh app:run
    restart: unless-stopped
    environment:
      DB_HOST: "database"
      DB_HOST_PORT: "5432"
      DB_USER: "zulip"
      SSL_CERTIFICATE_GENERATION: "self-signed"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: "123456789"
      SECRETS_rabbitmq_password: "${ZULIP_RABBITMQ_PASS:?ZULIP_RABBITMQ_PASS}"
      SECRETS_postgres_password: "${ZULIP_POSTGRESS_PASS:?ZULIP_POSTGRESS_PASS}"
      SECRETS_memcached_password: "${ZULIP_MEMCACHED_PASS:?ZULIP_MEMCACHED_PASS}"
      SECRETS_redis_password: "${ZULIP_REDIS_PASS:?ZULIP_REDIS_PASS}"
      SECRETS_secret_key: "${ZULIP_SECRET_KEY:?ZULIP_SECRET_KEY}"
      SETTING_EXTERNAL_HOST: "chat.bojidar-bg.dev"
      SETTING_ZULIP_ADMINISTRATOR: "bojidar.marinov.bg@gmail.com"
      SETTING_EMAIL_HOST: "" # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: "noreply@example.com"
      SETTING_EMAIL_PORT: "587"
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"
      QUEUE_WORKERS_MULTIPROCESS: "True"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
      VIRTUAL_HOST: "chat.bojidar-bg.dev,translation.chat.bojidar-bg.dev"
      LETSENCRYPT_HOST: "chat.bojidar-bg.dev,translation.chat.bojidar-bg.dev"
      DISABLE_HTTPS: true
      LOADBALANCER_IPS: 172.18.0.0/16
      SETTING_EMAIL_BACKEND: 'django.core.mail.backends.filebased.EmailBackend'
      SETTING_EMAIL_FILE_PATH: '/var/log/zulip/emails'
    volumes:
      - "zulip:/data:rw"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576
volumes:
  zulip:
  postgresql-14:
  rabbitmq:
  redis:
