services:
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: unless-stopped

  dockergen:
    container_name: dockergen-nginx
    image: nginxproxy/docker-gen
    build:
      context: docker-gen
      dockerfile: Dockerfile.alpine
    pull_policy: build
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    environment:
      - 'LOG_FORMAT=$$host 0.0.0.0 - $$remote_user [$$time_local] "$$request" $$status $$body_bytes_sent "$$http_referer" "" "$$upstream_addr"' # DISABLE_ACCESS_LOGS=true

  acme:
    image: nginxproxy/acme-companion
    build:
      context: acme-companion
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=bojidar.marinov.bg@gmail.com
      - NGINX_DOCKER_GEN_CONTAINER=dockergen-nginx

volumes:
  certs:
  vhost:
  html:
  acme:
networks:
  default:
    ipam:
     config:
       - subnet: 172.18.0.0/16
