#!/bin/sh

pwd

if git show --no-patch | grep -E '\[(skip-ci|skip|no-update)\]|wip'; then
  exit
fi

echo "Updating..."

git submodule update --init --recursive

./gen-passwords.sh

docker compose --env-file ./config.env up -d --remove-orphans

